### ISSUE TITLE
Broken setup.py

### ISSUE THREAD

**Issue by camilomarino** [alelab-upenn/graph-neural-networks#4]
When trying to pip install the package, I get the following error:
```
ERROR: Command errored out with exit status 1:                                                                       
     command: /home/user/anaconda3/envs/mine/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tm
p/pip-req-build-wl4f41q2/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-wl4f41q2/setup.py'"'"';f=getattr(tokenize, '"'"'
open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'
"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-re0b057i                                                        
         cwd: /tmp/pip-req-build-wl4f41q2/                                                                               
    Complete output (5 lines):                                                                                           
    Traceback (most recent call last):                                                                                   
      File "<string>", line 1, in <module>                                                                               
      File "/tmp/pip-req-build-wl4f41q2/setup.py", line 3, in <module>                                                   
        with open("../README.md", "r", encoding="utf-8") as fh:                                                          
    FileNotFoundError: [Errno 2] No such file or directory: '../README.md'                                               
    ----------------------------------------
WARNING: Discarding file:///home/user/graph-neural-networks. Command errored out with exit status 1: python setup.py eg
g_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. 
```
This is caused by the line 3 of setup.py.

**Comment by camilomarino** [comment]
#5
